[package]
name = "ohlg"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { path = "../tfhe-rs/tfhe", features = [ "boolean", "integer", "shortint" ] }
bincode = "1.3.3"
once_cell = "1.8.0"
serde = { version = "1.0", features = ["derive"] }

[lint]
non_snake_case = "allow"